import { OemRequest, ProviderProfile } from '@/types/domain';
export const MOCK_OEM_REQUESTS: OemRequest[] = [
  {
    id: 'req-001',
    unternehmen: 'Rheinmetall AG',
    ansprechpartner: 'Dr. Klaus Müller',
    email: 'k.mueller@rheinmetall.com',
    betreff: 'Entwicklung einer robusten Kommunikationsschnittstelle',
    beschreibung: 'Wir suchen einen Dienstleister für die Konzeption und Entwicklung einer verschlüsselten Kommunikationsschnittstelle für unsere autonomen Fahrzeugsysteme. Erfahrung mit militärischen Standards (z.B. STANAG) ist erforderlich.',
    kategorie: 'Software',
    zeitraum: 'Q2 2026 - Q4 2026',
    erstelltAm: '10.12.2025',
  },
  {
    id: 'req-002',
    unternehmen: 'Hensoldt',
    ansprechpartner: 'Frau Sabine Meier',
    email: 's.meier@hensoldt.net',
    betreff: 'KI-basierte Bildauswertung für Sensorfusion',
    beschreibung: 'Gesucht wird ein Spezialistenteam für die Implementierung eines KI-Modells zur Echtzeit-Objekterkennung und Klassifizierung aus kombinierten Radar- und Infrarot-Sensordaten.',
    kategorie: 'KI/Data',
    zeitraum: 'Ab sofort',
    erstelltAm: '08.12.2025',
  },
  {
    id: 'req-003',
    unternehmen: 'Krauss-Maffei Wegmann',
    ansprechpartner: 'Herr Jörg Schmidt',
    email: 'j.schmidt@kmweg.de',
    betreff: 'Hardware-Prototyping für neues Cockpit-Display',
    beschreibung: 'Wir benötigen Unterstützung bei der Erstellung von funktionsfähigen Prototypen für ein neues, gehärtetes Multifunktionsdisplay. Dies umfasst Platinenlayout, Gehäusedesign und Integrationstests.',
    kategorie: 'Hardware',
    zeitraum: '3 Monate',
    erstelltAm: '05.12.2025',
  },
];
export const MOCK_PROVIDER_PROFILES: ProviderProfile[] = [
  {
    id: 'prov-001',
    firmenname: 'CyberSec Solutions GmbH',
    ansprechpartner: 'Thomas Fischer',
    email: 't.fischer@cybersec.de',
    logoUrl: 'https://placehold.co/128x128/0f172a/f8fafc.png?text=CS',
    kurzbeschreibung: 'Spezialisten für gehärtete IT-Systeme und Kryptographie.',
    beschreibung: 'Die CyberSec Solutions GmbH bietet seit über 15 Jahren maßgeschneiderte Sicherheitslösungen für den öffentlichen und militärischen Sektor. Unsere Kernkompetenzen liegen in der Ende-zu-Ende-Verschlüsselung, Penetration Testing und der Entwicklung sicherer Software nach BSI-Standards.',
    schwerpunkte: ['Softwareentwicklung', 'Beratung/Strategie'],
    standort: 'München, Deutschland',
    website: 'https://cybersec.de',
  },
  {
    id: 'prov-002',
    firmenname: 'AI-Driven Dynamics',
    ansprechpartner: 'Dr. Lena Weber',
    email: 'l.weber@ai-dynamics.com',
    logoUrl: 'https://placehold.co/128x128/334155/f8fafc.png?text=AD',
    kurzbeschreibung: 'Führend in KI-gestützter Datenanalyse und Sensorfusion.',
    beschreibung: 'Unser Team aus Datenwissenschaftlern und Ingenieuren entwickelt fortschrittliche Algorithmen für die autonome Systemsteuerung und Lagebilderstellung. Wir haben Erfahrung in der Verarbeitung großer, heterogener Datenmengen in Echtzeit.',
    schwerpunkte: ['KI & Data', 'Systemintegration'],
    standort: 'Aachen, Deutschland',
    website: 'https://ai-dynamics.com',
  },
  {
    id: 'prov-003',
    firmenname: 'Prototyp Werkstatt Berlin',
    ansprechpartner: 'Markus Klein',
    email: 'm.klein@pwb.berlin',
    logoUrl: 'https://placehold.co/128x128/94a3b8/f8fafc.png?text=PWB',
    kurzbeschreibung: 'Schnelles Prototyping für Elektronik und Mechanik.',
    beschreibung: 'Wir setzen Ideen schnell in greifbare Ergebnisse um. Von einzelnen Platinen bis hin zu kompletten mechatronischen Baugruppen – unsere Werkstatt ist für die schnelle und flexible Fertigung von Prototypen und Kleinserien ausgestattet.',
    schwerpunkte: ['Prototypen/MVP', 'Systemintegration', 'Sonstiges'],
    standort: 'Berlin, Deutschland',
    website: 'https://pwb.berlin',
  },
];